// ==============================================================================
// uploads.go — Upload management handlers
//
// Upload endpoints manage the upload lifecycle: requesting an upload grant
// (presigned URL), checking upload status, and triggering validation.
//
// All endpoints require authentication.  Upload targets are always derived
// server-side from the authenticated identity and site metadata — clients
// never provide S3 keys or owner IDs (VISION.md §8.4, §13.2).
//
// Upload grants are scoped to a specific staging key:
//
//	staging/users/{userId}/uploads/{uploadId}/source.zip   (zip upload)
//	staging/users/{userId}/uploads/{uploadId}/index.html   (single-file upload)
//
// The client cannot influence the destination key.  The key is derived from
// the authenticated user's Cognito sub and a server-generated upload ID.
// ==============================================================================

package handler

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"time"

	"backend/go-api/internal/auth"
	"backend/go-api/internal/metadata"
	"backend/go-api/internal/metrics"
	"backend/go-api/internal/response"
)

// ==============================================================================
// UploadsHandler — Upload grant issuance and status tracking
// ==============================================================================

// UploadsHandler implements the upload endpoints backed by site metadata,
// upload records, a presigned-URL generator, and a direct S3 content store.
// Every method derives the owner identity from the authenticated request
// context — clients never provide owner IDs or S3 keys.
type UploadsHandler struct {
	siteRepo     metadata.SiteMetadataRepository
	uploadRepo   metadata.UploadRecordsRepository
	presign      PresignClient
	contentStore ContentStore
	callbacks    CallbackRegistrar
	bucket       string
	sitesDomain  string
	emitter      *metrics.Emitter
}

// NewUploadsHandler creates an UploadsHandler with the given dependencies.
//   - siteRepo:     used to verify site ownership before issuing grants
//   - uploadRepo:   used to create and read upload records
//   - presign:      generates presigned S3 PUT URLs
//   - contentStore: reads/writes S3 staging and published content
//   - callbacks:    registers published site hostnames on the Cognito app client
//   - bucket:       S3 bucket name for staging and published content
//   - sitesDomain:  base domain for hosted sites (e.g. sites.example.com)
//   - emitter:      emits upload lifecycle metrics via EMF
func NewUploadsHandler(
	siteRepo metadata.SiteMetadataRepository,
	uploadRepo metadata.UploadRecordsRepository,
	presign PresignClient,
	contentStore ContentStore,
	callbacks CallbackRegistrar,
	bucket string,
	sitesDomain string,
	emitter *metrics.Emitter,
) *UploadsHandler {
	return &UploadsHandler{
		siteRepo:     siteRepo,
		uploadRepo:   uploadRepo,
		presign:      presign,
		contentStore: contentStore,
		callbacks:    callbacks,
		bucket:       bucket,
		sitesDomain:  sitesDomain,
		emitter:      emitter,
	}
}

// ==============================================================================
// Upload type — controls the staging key suffix
// ==============================================================================

// UploadType classifies the kind of content being uploaded.
type UploadType string

const (
	UploadTypeZip   UploadType = "zip"   // Complete site archive (e.g. Hugo-generated zip)
	UploadTypeIndex UploadType = "index" // Single index.html file
)

// Presigned URL expiration — 15 minutes is enough for the client to start
// the upload while limiting the window for misuse.
const presignExpiration = 15 * time.Minute

// Maximum upload sizes — enforced by the validation worker, documented here
// for the presigned URL metadata.  The presigned PUT URL itself does not
// enforce a size range (that would require a POST policy), but the upload
// record carries these limits for the worker to enforce.
const (
	maxZipSizeBytes   = 100 * 1024 * 1024 // 100 MiB compressed
	maxIndexSizeBytes = 5 * 1024 * 1024   // 5 MiB for a single HTML file
)

// validateUploadType returns the canonical UploadType for the given string,
// or an error if the type is not recognised.
func validateUploadType(t string) (UploadType, error) {
	switch t {
	case "zip":
		return UploadTypeZip, nil
	case "index":
		return UploadTypeIndex, nil
	default:
		return "", fmt.Errorf("upload type must be %q or %q, got %q", UploadTypeZip, UploadTypeIndex, t)
	}
}

// stagingKey builds the S3 staging key for an upload.  The key is derived
// entirely from server-side values — the user ID from Cognito claims and the
// upload ID generated by the backend.
func stagingKey(userID, uploadID string, ut UploadType) string {
	suffix := "index.html"
	if ut == UploadTypeZip {
		suffix = "source.zip"
	}
	return fmt.Sprintf("staging/users/%s/uploads/%s/%s", userID, uploadID, suffix)
}

// contentType returns the MIME type for the upload type.
func contentType(ut UploadType) string {
	if ut == UploadTypeZip {
		return "application/zip"
	}
	return "text/html"
}

// ==============================================================================
// Request / response types
// ==============================================================================

// createUploadRequest is the JSON body expected by CreateUpload.
type createUploadRequest struct {
	SiteID string `json:"site_id"`
	Type   string `json:"type"` // "zip" or "index"
}

// uploadGrantResponse is the JSON shape returned after a successful grant.
type uploadGrantResponse struct {
	UploadID     string `json:"upload_id"`
	PresignedURL string `json:"presigned_url"`
	StagingKey   string `json:"staging_key"`
	ExpiresAt    string `json:"expires_at"`
}

// uploadStatusResponse is the JSON shape returned for upload status queries.
type uploadStatusResponse struct {
	UploadID         string                   `json:"upload_id"`
	SiteID           string                   `json:"site_id"`
	Status           string                   `json:"status"`
	S3StagingKey     string                   `json:"staging_key"`
	ValidationResult *metadata.ValidationResult `json:"validation_result,omitempty"`
	CreatedAt        string                   `json:"created_at"`
	UpdatedAt        string                   `json:"updated_at"`
}

// ==============================================================================
// POST /api/uploads — Request an upload grant for a site
//
// The backend:
//  1. Parses the request for site_id and upload type
//  2. Verifies the site belongs to the authenticated user
//  3. Generates a unique upload ID
//  4. Creates an upload record (status=pending)
//  5. Generates a presigned S3 PUT URL scoped to the staging key
//  6. Returns the upload ID, presigned URL, staging key, and expiration
//
// The client never provides S3 keys, owner IDs, or any part of the staging
// prefix — all are derived server-side (VISION.md §8.4, §13.2).
// ==============================================================================

func (h *UploadsHandler) CreateUpload(w http.ResponseWriter, r *http.Request) {
	id := auth.RequestIdentity(r)
	if id == nil {
		response.Unauthorized(w, "")
		return
	}

	// 1. Parse and validate the request body.
	var req createUploadRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		response.BadRequest(w, "Invalid request body: must be JSON with site_id and type fields")
		return
	}

	if req.SiteID == "" {
		response.BadRequest(w, "site_id is required")
		return
	}

	uploadType, err := validateUploadType(req.Type)
	if err != nil {
		response.BadRequest(w, err.Error())
		return
	}

	ctx := r.Context()

	// 2. Verify the site exists and belongs to the authenticated user.
	//    GetSite uses userID as part of the PK, so a wrong-user request
	//    returns nil → 404 — no explicit ownership check needed.
	site, err := h.siteRepo.GetSite(ctx, id.UserID, req.SiteID)
	if err != nil {
		slog.Error("get site for upload failed", "user_id", id.UserID, "site_id", req.SiteID, "error", err)
		response.InternalError(w, err)
		return
	}
	if site == nil {
		response.NotFound(w, "Site not found")
		return
	}
	if site.Disabled {
		response.BadRequest(w, "Cannot upload to a disabled site")
		return
	}

	// 3. Generate a unique upload ID.
	uploadID := newUploadID()

	// 4. Derive the staging key server-side.
	key := stagingKey(id.UserID, uploadID, uploadType)

	// 5. Create the upload record (status = pending).
	upload := metadata.Upload{
		UploadID:     uploadID,
		UserID:       id.UserID,
		SiteID:       req.SiteID,
		Status:       metadata.UploadStatusPending,
		S3StagingKey: key,
	}
	if err := h.uploadRepo.CreateUpload(ctx, upload); err != nil {
		slog.Error("create upload record failed", "user_id", id.UserID, "upload_id", uploadID, "error", err)
		response.InternalError(w, err)
		return
	}

	// 6. Generate the presigned PUT URL scoped to the staging key.
	presignReq := PresignRequest{
		Bucket:      h.bucket,
		Key:         key,
		ContentType: contentType(uploadType),
		Expires:     presignExpiration,
	}

	presignResult, err := h.presign.PresignPutObject(ctx, presignReq)
	if err != nil {
		slog.Error("presign put object failed", "user_id", id.UserID, "upload_id", uploadID, "key", key, "error", err)
		response.InternalError(w, err)
		return
	}

	slog.Info("upload grant issued",
		"user_id", id.UserID,
		"upload_id", uploadID,
		"site_id", req.SiteID,
		"type", uploadType,
		"staging_key", key,
	)

	h.emitter.EmitUploadEvent("requested", string(uploadType), "")

	response.JSON(w, http.StatusCreated, uploadGrantResponse{
		UploadID:     uploadID,
		PresignedURL: presignResult.URL,
		StagingKey:   key,
		ExpiresAt:    presignResult.ExpiresAt.UTC().Format(time.RFC3339),
	})
}

// ==============================================================================
// POST /api/uploads/{id}/complete — Signal upload completion
//
// The frontend calls this after the presigned S3 PUT succeeds.  The backend:
//  1. Verifies the upload record exists and belongs to the authenticated user
//  2. Verifies the current status is "pending" (exactly-once guard)
//  3. Transitions the status to "uploaded"
//
// The transition from pending → uploaded is the explicit trigger boundary:
// the backend then validates and publishes synchronously (publish.go), so
// the response carries the final status (published or failed).
//
// This endpoint is idempotent: if the status is already "uploaded" or later,
// it returns 200 with the current status.  If the status is "pending",
// it transitions to "uploaded".
// ==============================================================================

// uploadCompleteResponse is the JSON shape returned after signalling completion.
type uploadCompleteResponse struct {
	UploadID string `json:"upload_id"`
	Status   string `json:"status"`
}

func (h *UploadsHandler) CompleteUpload(w http.ResponseWriter, r *http.Request) {
	id := auth.RequestIdentity(r)
	if id == nil {
		response.Unauthorized(w, "")
		return
	}

	uploadID := r.PathValue("id")
	if uploadID == "" {
		response.BadRequest(w, "upload ID is required")
		return
	}

	ctx := r.Context()

	upload, err := h.uploadRepo.GetUpload(ctx, id.UserID, uploadID)
	if err != nil {
		slog.Error("get upload for completion failed", "user_id", id.UserID, "upload_id", uploadID, "error", err)
		response.InternalError(w, err)
		return
	}
	if upload == nil {
		response.NotFound(w, "Upload not found")
		return
	}

	// Idempotent: if already beyond pending, return current status.
	if upload.Status != metadata.UploadStatusPending {
		slog.Info("upload completion already signalled",
			"user_id", id.UserID,
			"upload_id", uploadID,
			"status", upload.Status,
		)
		response.JSON(w, http.StatusOK, uploadCompleteResponse{
			UploadID: uploadID,
			Status:   string(upload.Status),
		})
		return
	}

	// Transition pending → uploaded.
	if err := h.uploadRepo.UpdateUploadStatus(ctx, id.UserID, uploadID, metadata.UploadStatusUploaded, nil); err != nil {
		slog.Error("update upload status to uploaded failed", "user_id", id.UserID, "upload_id", uploadID, "error", err)
		response.InternalError(w, err)
		return
	}

	slog.Info("upload marked as complete",
		"user_id", id.UserID,
		"upload_id", uploadID,
		"site_id", upload.SiteID,
	)

	h.emitter.EmitUploadEvent("completed", string(uploadTypeFromKey(upload.S3StagingKey)), "")

	status, err := h.publish(ctx, id, *upload)
	if err != nil {
		slog.Error("publish upload failed", "user_id", id.UserID, "upload_id", uploadID, "error", err)
		response.InternalError(w, err)
		return
	}

	response.JSON(w, http.StatusOK, uploadCompleteResponse{
		UploadID: uploadID,
		Status:   string(status),
	})
}

// ==============================================================================
// POST /api/uploads/paste — Pasted-HTML upload (VISION.md §11.3)
//
// The frontend sends an HTML document as a JSON string.  The backend:
//  1. Verifies the site exists and belongs to the authenticated user
//  2. Generates a unique upload ID
//  3. Writes the HTML content directly to S3 staging as index.html
//  4. Creates an upload record with status "uploaded" (content already staged)
//  5. Returns the upload ID and status
//
// Unlike the presigned-URL flow, the backend receives the content directly
// and handles the S3 PutObject call.  The upload starts in "uploaded" state
// because the content is already staged when this call returns.
//
// Limits:
//   - Maximum HTML payload size: 5 MiB (enforced by the handler before storage)
// ==============================================================================

// pasteUploadRequest is the JSON body expected by CreatePasteUpload.
type pasteUploadRequest struct {
	SiteID string `json:"site_id"`
	HTML   string `json:"html"`
}

// Max paste payload size — 5 MiB of UTF-8 text.
const maxPasteBytes = 5 * 1024 * 1024

// pasteUploadResponse is the JSON shape returned after a successful paste upload.
type pasteUploadResponse struct {
	UploadID   string `json:"upload_id"`
	SiteID     string `json:"site_id"`
	Status     string `json:"status"`
	StagingKey string `json:"staging_key"`
	CreatedAt  string `json:"created_at"`
}

func (h *UploadsHandler) CreatePasteUpload(w http.ResponseWriter, r *http.Request) {
	id := auth.RequestIdentity(r)
	if id == nil {
		response.Unauthorized(w, "")
		return
	}

	// 1. Parse and validate the request body — limit read size.
	r.Body = http.MaxBytesReader(w, r.Body, maxPasteBytes+1024) // 1 KiB headroom for JSON envelope
	var req pasteUploadRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		if err.Error() == "http: request body too large" {
			response.BadRequest(w, "HTML content exceeds maximum size of 5 MiB")
			return
		}
		response.BadRequest(w, "Invalid request body: must be JSON with site_id and html fields")
		return
	}

	if req.SiteID == "" {
		response.BadRequest(w, "site_id is required")
		return
	}
	if req.HTML == "" {
		response.BadRequest(w, "html field must not be empty")
		return
	}
	htmlBytes := []byte(req.HTML)
	if len(htmlBytes) > maxPasteBytes {
		response.BadRequest(w, fmt.Sprintf("HTML content exceeds maximum size of %d bytes", maxPasteBytes))
		return
	}

	ctx := r.Context()

	// 2. Verify the site exists and belongs to the authenticated user.
	site, err := h.siteRepo.GetSite(ctx, id.UserID, req.SiteID)
	if err != nil {
		slog.Error("get site for paste upload failed", "user_id", id.UserID, "site_id", req.SiteID, "error", err)
		response.InternalError(w, err)
		return
	}
	if site == nil {
		response.NotFound(w, "Site not found")
		return
	}
	if site.Disabled {
		response.BadRequest(w, "Cannot upload to a disabled site")
		return
	}

	// 3. Generate a unique upload ID and derive the staging key.
	uploadID := newUploadID()
	key := stagingKey(id.UserID, uploadID, UploadTypeIndex)

	// 4. Write the HTML content directly to S3 staging.
	if err := h.contentStore.PutContent(ctx, ContentStoreRequest{
		Bucket:      h.bucket,
		Key:         key,
		Body:        htmlBytes,
		ContentType: "text/html",
	}); err != nil {
		slog.Error("put content to staging failed", "user_id", id.UserID, "upload_id", uploadID, "key", key, "error", err)
		response.InternalError(w, err)
		return
	}

	// 5. Create the upload record — starts in "uploaded" state (content already staged).
	upload := metadata.Upload{
		UploadID:     uploadID,
		UserID:       id.UserID,
		SiteID:       req.SiteID,
		Status:       metadata.UploadStatusUploaded,
		S3StagingKey: key,
	}
	if err := h.uploadRepo.CreateUpload(ctx, upload); err != nil {
		slog.Error("create paste upload record failed", "user_id", id.UserID, "upload_id", uploadID, "error", err)
		response.InternalError(w, err)
		return
	}

	status, err := h.publish(ctx, id, upload)
	if err != nil {
		slog.Error("publish paste upload failed", "user_id", id.UserID, "upload_id", uploadID, "error", err)
		response.InternalError(w, err)
		return
	}

	// Read back to get the canonical timestamp.
	created, err := h.uploadRepo.GetUpload(ctx, id.UserID, uploadID)
	if err != nil || created == nil {
		slog.Error("read back paste upload failed", "upload_id", uploadID, "error", err)
		response.InternalError(w, fmt.Errorf("upload record was created but could not be read back"))
		return
	}

	slog.Info("paste upload created",
		"user_id", id.UserID,
		"upload_id", uploadID,
		"site_id", req.SiteID,
		"size_bytes", len(htmlBytes),
	)

	// Paste uploads start in "uploaded" state — emit both requested and completed.
	h.emitter.EmitUploadEvent("requested", "paste", "")
	h.emitter.EmitUploadEvent("completed", "paste", "")

	response.JSON(w, http.StatusCreated, pasteUploadResponse{
		UploadID:   uploadID,
		SiteID:     req.SiteID,
		Status:     string(status),
		StagingKey: key,
		CreatedAt:  created.CreatedAt.UTC().Format(time.RFC3339),
	})
}

// ==============================================================================
// GET /api/uploads/{id} — Get upload status
//
// Returns the current status (pending, uploaded, validating, published, failed)
// and, if validation has completed, the validation result.
//
// Ownership is enforced at the data layer: GetUpload queries by userID +
// uploadID, so a request for another user's upload returns nil → 404.
// ==============================================================================

func (h *UploadsHandler) GetUploadStatus(w http.ResponseWriter, r *http.Request) {
	id := auth.RequestIdentity(r)
	if id == nil {
		response.Unauthorized(w, "")
		return
	}

	uploadID := r.PathValue("id")
	if uploadID == "" {
		response.BadRequest(w, "upload ID is required")
		return
	}

	upload, err := h.uploadRepo.GetUpload(r.Context(), id.UserID, uploadID)
	if err != nil {
		slog.Error("get upload status failed", "user_id", id.UserID, "upload_id", uploadID, "error", err)
		response.InternalError(w, err)
		return
	}
	if upload == nil {
		response.NotFound(w, "Upload not found")
		return
	}

	slog.Info("upload status retrieved",
		"user_id", id.UserID,
		"upload_id", uploadID,
		"status", upload.Status,
	)

	response.JSON(w, http.StatusOK, uploadStatusResponse{
		UploadID:         upload.UploadID,
		SiteID:           upload.SiteID,
		Status:           string(upload.Status),
		S3StagingKey:     upload.S3StagingKey,
		ValidationResult: upload.ValidationResult,
		CreatedAt:        upload.CreatedAt.UTC().Format(time.RFC3339),
		UpdatedAt:        upload.UpdatedAt.UTC().Format(time.RFC3339),
	})
}

// ==============================================================================
// Internal helpers
// ==============================================================================

// newUploadID generates a unique upload identifier.
// Uses crypto/rand to produce a hex string prefixed with "upload_".
func newUploadID() string {
	b := make([]byte, 12)
	if _, err := rand.Read(b); err != nil {
		// crypto/rand.Read can fail only on a broken system; fall back to a
		// timestamp-based suffix so callers don't have to handle the error.
		b = []byte(fmt.Sprintf("%d", time.Now().UnixNano()))
	}
	return fmt.Sprintf("upload_%x", b)
}

// uploadTypeFromKey infers the upload type from the staging key suffix.
// Staging keys end with "source.zip" (zip) or "index.html" (index/paste).
func uploadTypeFromKey(key string) UploadType {
	if strings.HasSuffix(key, "source.zip") {
		return UploadTypeZip
	}
	return UploadTypeIndex
}
